# Generated by Django 2.2.5 on 2019-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misi', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('sasaran', models.CharField(max_length=100)),
                ('indikator', models.CharField(max_length=100)),
            ],
        ),
    ]
