# Generated by Django 2.2.5 on 2019-09-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indikator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sasaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sasaran', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tujuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='misi',
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='sasaran',
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='tujuan',
        ),
    ]
